### ISSUE TITLE
Customer Segment

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#11]
Please describe your target customers in more detail. Outline how much revenue they make, the cost of piracy (cost of not having your service), and the number of potential customers in the market place.

**Comment by mperezh480** [comment]
I added information on the top two businesses we are targeting and overall more information on our target customers.

**Comment by GeorgLink** [comment]
Where did you add this information? I was looking here: https://github.com/jinbe-808/OATs/blob/master/T2.md and could not find an assessment of your potential customer base (number of potential customers and their willingness to pay for your service).

**Comment by mperezh480** [comment]
I added it to the wrong assignment. I will change it thanks.
