### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#13]
Please include a list of channels in addition to the description you already have. Suggestion to split the description into one paragraph for each channel. Describe how each channel helps to have the kind of customer relationship you seek.

**Comment by hchubaldo** [comment]
I broke up the first paragraph so hopefully there isn't a wall of text.

**Comment by GeorgLink** [comment]
How about formatting like this

> General description paragraph of channel strategy ...
> 
> **Website**: Description of this channel and how it provides value
> 
> **Next channel**: Description of this channel and how it provides value

You can add more channels. This will give a reader a quick overview of all channels (bold words).
