### ISSUE TITLE
Customer Relationships

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#14]
There are many ideas in a single paragraph. Please create more structure, describing your overall approach and then a separate paragraph for each specific activity.

**Comment by hchubaldo** [comment]
I tried to break up a few of the paragraphs.

**Comment by GeorgLink** [comment]
The ideas may also need to be reorganized to make more sense. Maybe add three headings: one for **Customers**, one for **Channels**, and one for a description of the **Customer Relationship**.

Under each section heading, maybe have a clear structure, see #13 for an idea for the Channel section.

**Comment by hchubaldo** [comment]
I tried to move a few things around to improve the flow.

**Comment by GeorgLink** [comment]
It's better. I will accept it as is.

**Comment by GeorgLink** [comment]
PS you can close this issue when you plan to make no more changes
