### ISSUE TITLE
Key Activities

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#15]
Please separate out the different activities into separate paragraphs and describe how each helps deliver the value proposition.

**Comment by hchubaldo** [comment]
I tried to break it up a bit more like you suggested.

**Comment by GeorgLink** [comment]
The heading of the page was changed in https://github.com/jinbe-808/OATs/commit/6d32df8bf4bf817373cb210c8ff7638871f62595#diff-41c26a83e4531e16be3727634c5d9abb

If there is no specific reason, I suggest converting it back, to be aligned with the headings from the Business Model Canvas.

**Comment by GeorgLink** [comment]
The top part of the page reads like a value proposition, very much focused on the customer. A rewrite could put the activity that the business performs first.

**Comment by hchubaldo** [comment]
I moved the activities to the top. Not sure if the second part would be considered key resources. I feel it mentions our user base and brand name.

**Comment by hchubaldo** [comment]
I was able to figure it out after seeing the descriptions in the business model canvas.
