### ISSUE TITLE
Financial Plan

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#19]
Good collection of items to include in your financial plan.

- Please create tables with Dollar amounts. They may be estimated. Do include a source from which you arrived at your estimate (e.g., include a link to a office rental site for cost of office space).
- Please double check that you have all partners, resources, and processes represented in the financial estimates (this requires improving the other sections of the business plan as suggested).
- Consider including startup funds for registering company.
- Please remove the task description from the final document.

**Comment by hchubaldo** [comment]
Money values were added to the tables.

**Comment by GeorgLink** [comment]
FYI: I shared in class what the 3-year plan table looks like:

Item | Year 1 | Year 2 | Year 3
---|---|---|---
Revenue | + $$$ | + $$$ | + $$$
Cost | - $$$ | - $$$ | - $$$
**Profit/Loss** | **+/- $$$** | **+/- $$$** | **+/- $$$**

Simply create a line for each item.
The revenue would probably increase over the years, as you start growing your business.


The table for startup funds should also contain a total amount.

**Comment by hchubaldo** [comment]
I added the 3-Year Plan at the bottom

**Comment by GeorgLink** [comment]
okay
