### ISSUE TITLE
Visual Business Model Canvas

### ISSUE THREAD

**Issue by GeorgLink** [jinbe-808/OATs#8]
Please create a visual business model canvas. Each field of the table should summarize your business in a few bullet points.

**Comment by GeorgLink** [comment]
Please use the Business Model Canvas layout for displaying it. Something like the [in this gist](https://gist.github.com/pierrebeaucamp/fa2fec4f859d8d9ce3d0)

**Comment by hchubaldo** [comment]
I included a lean canvas model in the READ_ME

**Comment by GeorgLink** [comment]
Thank you for adding the table. Please use the headings as they are in the Business Model Canvas: https://en.wikipedia.org/wiki/Business_Model_Canvas#/media/File:Business_Model_Canvas.png

(I just saw that the gist I shared had the wrong headings, I am sorry!)

**Comment by hchubaldo** [comment]
I fixed the canvas I had before to fit the Business Model Canvas.
